musicalia/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tracks/', include('tracks.urls')),
]

tracks/urls.py
from django.urls import path

from . import views

app_name = 'tracks'

urlpatterns = [
    path('', views.track_list, name='track_list'),
    path('<int:pk>/', views.track_detail, name='track_detail'),
]

artists/models.py
from django.db import models


class Artist(models.Model):
    class Scope(models.TextChoices):
        LOCAL = 'L', 'Local'
        NATIONAL = 'N', 'Nacional'
        INTERNATIONAL = 'I', 'Internacional'

    name = models.CharField(max_length=256)
    starting_year = models.PositiveSmallIntegerField()
    website = models.URLField(blank=True)
    scope = models.CharField(
        max_length=1,
        choices=Scope,
        default=Scope.INTERNATIONAL,
    )

    def __str__(self):
        return self.name

tracks/models.py
from django.db import models


class Track(models.Model):
    name = models.CharField(max_length=256)
    artist = models.ForeignKey(
        'artists.Artist',
        on_delete=models.CASCADE,
        related_name='tracks',
    )
    length = models.IntegerField()  # in seconds
    num_visits = models.PositiveBigIntegerField(default=0)

    def __str__(self):
        return self.name

artists/views.py
from django.shortcuts import render

# Create your views here.

tracks/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render

from .models import Track


def track_list(request: HttpRequest) -> HttpResponse:
    tracks = Track.objects.all()
    return render(request, 'tracks/track/list.html', dict(tracks=tracks))


def track_detail(request: HttpRequest, pk: int) -> HttpResponse:
    track = Track.objects.get(pk=pk)
    return render(request, 'tracks/track/detail.html', dict(track=track))

tracks/templates/tracks/base.html
<html>
<head>
  <title>Musicalia</title>
</head>
<body>
  <h1>♫ Canciones</h1>
  <h2>{% block subtitle %}{% endblock %}</h2>
  {% block contents %}{% endblock %}
</body>
</html>

tracks/templates/tracks/track/detail.html
{% extends "tracks/base.html" %}

{% block subtitle %}{{ track.name }}{% endblock %}

{% block contents %}
<table>
  <tr>
    <th>Nombre</th>
    <td>{{ track.name }}</td>
  </tr>
  <tr>
    <th>Cantante</th>
    <td>{{ track.singer }}</td>
  </tr>
  <tr>
    <th>Duración</th>
    <td>{{ track.length }} minutos</td>
  </tr>
</table>
{% endblock %}

tracks/templates/tracks/track/list.html
{% extends "tracks/base.html" %}

{% block subtitle %}Lista{% endblock %}

{% block contents %}
<ul>
  {% for track in tracks %}
    <li><a href="{% url 'tracks:track_detail' track.pk %}">{{ track }}</a></li>
  {% endfor %}
</ul>
{% endblock %}